repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    - id: check-toml
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.1.0
    hooks:
    - id: eslint
      additional_dependencies:
      - eslint
      - "@typescript-eslint/eslint-plugin@4.18.0"
      - "@nuxtjs/eslint-config-typescript@6.0.0"
      files: \.[jt]sx?|\.vue?$  # *.vue, *.js, *.jsx, *.ts and *.tsx
      args: [-c, ./.eslintrc.js]
